# permissions for end users to edit clusterdetectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: clusterdetector-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: plumber
    app.kubernetes.io/part-of: plumber
    app.kubernetes.io/managed-by: kustomize
  name: clusterdetector-editor-role
rules:
- apiGroups:
  - plumber.jnytnai0613.github.io
  resources:
  - clusterdetectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - plumber.jnytnai0613.github.io
  resources:
  - clusterdetectors/status
  verbs:
  - get
